version: "3.8"
services:
  frontend:
    build:
      context: ./crm-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./crm-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
